.TH crunchy-cli 1 "27 June 2022" "crunchy-cli" "Crunchyroll Cli Client"

.SH NAME
crunchy-cli - A cli for downloading videos and entire series from crunchyroll.

.SH SYNOPSIS
crunchy-cli [\fB-h\fR] [\fB-p\fR \fIPROXY\fR] [\fB-q\fR] [\fB-v\fR]
.br
crunchy-cli help
.br
crunchy-cli login [\fB--persistent\fR] [\fB--session-id\fR \fISESSION_ID\fR] [\fIusername\fR, \fIpassword\fR]
.br
crunchy-cli download [\fB-a\fR \fIAUDIO\fR] [\fB-s\fR \fISUBTITLE\fR] [\fB-d\fR \fIDIRECTORY\fR] [\fB-o\fR \fIOUTPUT\fR] [\fB-r\fR \fIRESOLUTION\fR] [\fB-g\fR \fIGOROUTINES\fR] \fIURLs...\fR
.br
crunchy-cli archive [\fB-l\fR \fILANGUAGE\fR] [\fB-d\fR \fIDIRECTORY\fR] [\fB-o\fR \fIOUTPUT\fR] [\fB-m\fR \fIMERGE BEHAVIOR\fR] [\fB-c\fR \fICOMPRESS\fR] [\fB-r\fR \fIRESOLUTION\fR] [\fB-g\fR \fIGOROUTINES\fR] \fIURLs...\fR
.br
crunchy-cli update [\fB-i\fR \fIINSTALL\fR]

.SH DESCRIPTION
.TP
With \fBcrunchy-cli\fR you can easily download video and series from crunchyroll.
.TP

Note that you need an \fBcrunchyroll premium\fR account in order to use this tool!

.SH GENERAL OPTIONS
.TP
This options can be passed to every action.
.TP

\fB-h, --help\fR
Shows help.
.TP

\fB-p, --proxy PROXY\fR
Sets a proxy through which all traffic will be routed.
.TP

\fB-q, --quiet\fR
Disables all output.
.TP

\fB-v, --verbose\fR
Shows verbose output.
.TP

\fB--lang\fR
Set language to use. If not set, it's received from the system locale dynamically. Choose from: ar-ME, ar-SA, de-DE, en-US, es-419, es-ES, es-LA, fr-FR, it-IT, ja-JP, pt-BR, pt-PT, ru-RU, zh-CN.
.TP

\fB--useragent\fR
Useragent to do all request with.
.TP

\fB--version\fR
Shows the current cli version.

.SH LOGIN COMMAND
This command logs in to crunchyroll and stores the session id or credentials on the drive. This needs to be done before calling other commands since they need a valid login to operate.
.TP

\fB--persistent\fR
Stores the given credentials permanent on the drive. The *nix path for it is $HOME/.config/crunchy.
.br
NOTE: The credentials are stored in plain text and if you not use \fB--session-id\fR your credentials are used (if you not use the \fB--persistent\fR flag only a session id gets stored regardless if you login with username/password or a session id).
.TP

\fB--session-id SESSION_ID\fR
Login via a session id (which can be extracted from a crunchyroll browser cookie) instead of using username and password.

.SH DOWNLOAD COMMAND
A command to simply download videos. The output file is stored as a \fI.ts\fR file. \fIffmpeg\fR has to be installed if you want to change the Format the videos are stored in.
.TP

\fB-a, --audio AUDIO\fR
Forces to download videos with the given audio locale. If no video with this audio locale is available, nothing will be downloaded. Available locales are: ja-JP, en-US, es-419, es-LA, es-ES, fr-FR, pt-PT, pt-BR, it-IT, de-DE, ru-RU, ar-SA, ar-ME.
.TP

\fB-s, --subtitle SUBTITLE\fR
Forces to download the videos with subtitles in the given locale / language. If no video with this subtitle locale is available, nothing will be downloaded. Available locales are: ja-JP, en-US, es-419, es-LA, es-ES, fr-FR, pt-PT, pt-BR, it-IT, de-DE, ru-RU, ar-SA, ar-ME.
.TP

\fB-d, --directory DIRECTORY\fR
The directory to download all files to.
.TP

\fB-o, --output OUTPUT\fR
Name of the output file. Formatting is also supported, so if the name contains one or more of the following things, they will get replaced.
    {title} » Title of the video.
    {series_name} » Name of the series.
    {season_name} » Name of the season.
    {season_number} » Number of the season.
    {episode_number} » Number of the episode.
    {resolution} » Resolution of the video.
    {fps} » Frame Rate of the video.
    {audio} » Audio locale of the video.
    {subtitle} » Subtitle locale of the video.
.TP

\fB-r, resolution RESOLUTION\fR
The video resolution. Can either be specified via the pixels (e.g. 1920x1080), the abbreviation for pixels (e.g. 1080p) or "common-use" words (e.g. best).
    Available pixels: 1920x1080, 1280x720, 640x480, 480x360, 426x240.
    Available abbreviations: 1080p, 720p, 480p, 360p, 240p.
    Available common-use words: best (best available resolution), worst (worst available resolution).
.TP

\fB-g, --goroutines GOROUTINES\fR
Sets the number of parallel downloads for the segments the final video is made of. Default is the number of cores the computer has.

.SH ARCHIVE COMMAND
This command behaves like \fBdownload\fR besides the fact that it requires \fIffmpeg\fR and stores the output only to .mkv files.
.TP

\fB-l, --language LANGUAGE\fR
Audio locales which should be downloaded. Can be used multiple times. Available locales are: ja-JP, en-US, es-419, es-LA, es-ES, fr-FR, pt-PT, pt-BR, it-IT, de-DE, ru-RU, ar-SA, ar-ME.
.TP

\fB-s, --sublang LANGUAGE\fR
Subtitle languages to use, by default all are included. Can be used multiple times. Available locales are: ja-JP, en-US, es-419, es-LA, es-ES, fr-FR, pt-PT, pt-BR, it-IT, de-DE, ru-RU, ar-SA, ar-ME.
.TP

\fB-d, --directory DIRECTORY\fR
The directory to download all files to.
.TP

\fB-o, --output OUTPUT\fR
Name of the output file. Formatting is also supported, so if the name contains one or more of the following things, they will get replaced.
    {title} » Title of the video.
    {series_name} » Name of the series.
    {season_name} » Name of the season.
    {season_number} » Number of the season.
    {episode_number} » Number of the episode.
    {resolution} » Resolution of the video.
    {fps} » Frame Rate of the video.
    {audio} » Audio locale of the video.
    {subtitle} » Subtitle locale of the video.
.TP

\fB-m, --merge MERGE BEHAVIOR\fR
Sets the behavior of the stream merging. Valid behaviors are 'auto', 'audio', 'video'. \fB--audio\fR stores one video and only the audio of all other languages, \fBvideo\fR stores all videos of the given languages and their audio, \fBauto\fR (which is the default) only behaves like video if the length of two videos are different (and only for the two videos), else like audio.
.TP

\fB-c, --compress COMPRESS\fR
If is set, all output will be compresses into an archive (every url generates a new one). This flag sets the name of the compressed output file. The file ending specifies the compression algorithm. The following algorithms are supported: gzip, tar, zip.
Just like \fB--output\fR the name can be formatted. But the only option available here is \fI{series_name}\fR.
.TP

\fB-r, resolution RESOLUTION\fR
The video resolution. Can either be specified via the pixels (e.g. 1920x1080), the abbreviation for pixels (e.g. 1080p) or "common-use" words (e.g. best).
    Available pixels: 1920x1080, 1280x720, 640x480, 480x360, 426x240.
    Available abbreviations: 1080p, 720p, 480p, 360p, 240p.
    Available common-use words: best (best available resolution), worst (worst available resolution).
.TP

\fB-g, --goroutines GOROUTINES\fR
Sets the number of parallel downloads for the segments the final video is made of. Default is the number of cores the computer has.
.TP

\fB--no-subtitle-optimizations DISABLE\fR
Disable subtitle optimizations which caused subtitle sizing and layout issues (https://github.com/crunchy-labs/crunchy-cli/issues/66).

.SH UPDATE COMMAND
Checks if a newer version is available.
.TP

\fB-i, --install INSTALL\fR
If given, the command tries to update the executable with the newer version (if a newer is available).

.SH URL OPTIONS
If you want to download only specific episode of a series, you could either pass every single episode url to the downloader (which is fine for 1 - 3 episodes) or use filtering.
It works pretty simple, just put a specific pattern surrounded by square brackets at the end of the url from the anime you want to download. A season and / or episode as well as a range from where to where episodes should be downloaded can be specified.
Use the list below to get a better overview what is possible
    ...[E5] - Download the fifth episode.
    ...[S1] - Download the full first season.
    ...[-S2] - Download all seasons up to and including season 2.
    ...[S3E4-] - Download all episodes from and including season 3, episode 4.
    ...[S1E4-S3] - Download all episodes from and including season 1, episode 4, until and including season 3.

In practise, it would look like this: \fIhttps://www.crunchyroll.com/series/12345678/example[S1E5-S3E2]\fR.

The \fBS\fR, followed by the number indicates the season number, \fBE\fR, followed by the number indicates an episode number. It doesn't matter if \fBS\fR, \fBE\fR or both are missing. Theoretically \fB[-]\fR is a valid pattern too. Note that \fBS\fR must always stay before \fBE\fR when used.

.SH EXAMPLES
Login via crunchyroll account email and password.
.br
$ crunchy-cli login user@example.com 12345678

Download a episode normally. Your system locale will be used for the video's audio.
.br
$ crunchy-cli download https://www.crunchyroll.com/watch/GRDKJZ81Y/alone-and-lonesome

Download a episode with 720p and name it to 'darling.mp4'. Note that you need \fBffmpeg\fR to save files which do not have '.ts' as file extension.
.br
$ crunchy-cli download -o "darling.mp4" -r 720p https://www.crunchyroll.com/watch/GRDKJZ81Y/alone-and-lonesome

Download a episode with japanese audio and american subtitles.
.br
$ crunchy-cli download -a ja-JP -s en-US https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E3-E5]

Stores the episode in a .mkv file.
.br
$ crunchy-cli archive https://www.crunchyroll.com/watch/GRDKJZ81Y/alone-and-lonesome

Downloads the first two episode of Darling in the FranXX and stores it compressed in a file.
.br
$ crunchy-cli archive -c "ditf.tar.gz" https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E1-E2]

.SH BUGS
If you notice any bug or want an enhancement, feel free to create a new issue or pull request in the GitHub repository.

.SH AUTHOR
Crunchy Labs Maintainers
.br
Source: https://github.com/crunchy-labs/crunchy-cli

.SH COPYRIGHT
Copyright (C) 2022 Crunchy Labs Maintainers

This program is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation, either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

